@host=http://localhost:3000

####
# @name root

get {{host}}

###
# @name register

post {{host}}/api/register
Content-Type: application/json

{
  "email": "hello@world.com",
  "password": "admin"
}

###

@register_token={{register.response.body.data.token}}

###
# @name login

post {{host}}/api/login
Content-Type: application/json

{
  "email": "hello@world.com",
  "password": "admin"
}

###

@login_token={{login.response.body.data.token}}

###
